# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: sergio.d.m.amaral@gmail.com
author_name: John Doe
contract_name: trader_app
deployment_language: python
preset_name: production
project_name: trader

